<?php

namespace Test\Ease\Html;

use Ease\Html\BodyTag;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:52.
 */
class BodyTagTest extends PairTagTest
{
    /**
     * @var BodyTag
     */
    protected $object;
    public $rendered = '<body>

<script>
// <![CDATA[
window.location = "login.php"
// ]]>
</script>
</body>';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        \Ease\WebPage::singleton()->cascadeStyles = [];
        \Ease\Document::singleton()->javaScripts  = [];
        $this->object                             = new \Ease\Html\BodyTag();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers Ease\Html\BodyTag::__construct
     */
    public function testConstructor()
    {
        parent::testConstructor();
    }

    /**
     * @covers Ease\Html\BodyTag::drawIfNotDrawn
     */
    public function testDrawIfNotDrawn($canBeEmpty = false)
    {
        $this->object->emptyContents();
        \Ease\WebPage::singleton()->cascadeStyles = [];
        \Ease\Document::singleton()->javaScripts  = [];
        parent::testDrawIfNotDrawn($canBeEmpty);
    }

    /**
     * @covers Ease\Html\BodyTag::draw
     */
    public function testDraw($whatWant = null)
    {
        parent::testDraw($whatWant);
    }

    /**
     * @covers Ease\Html\BodyTag::setObjectName
     */
    public function testSetObjectName()
    {
        $this->object->setObjectName();
        $this->assertEquals('body', $this->object->getObjectName());
    }
}
