<?php

declare(strict_types=1);

/**
 * This file is part of the EaseHtml package
 *
 * https://github.com/VitexSoftware/php-ease-html
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Ease\Html;

use Ease\Html\FieldSet;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:59:01.
 */
class FieldSetTest extends PairTagTest
{
    public string $rendered = '<fieldset><legend>test</legend>content</fieldset>';
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Ease\Html\FieldSet('test', 'content');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \Ease\Html\FieldSet::setLegend
     *
     * @todo   Implement testSetLegend().
     */
    public function testSetLegend(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Ease\Html\FieldSet::finalize
     *
     * @todo   Implement testFinalize().
     */
    public function testFinalize(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Ease\Html\FieldSet::getTagName
     */
    public function testGetTagName(): void
    {
        $this->assertEquals('test', $this->object->getTagName());
    }

    /**
     * @covers \Ease\Html\FieldSet::setObjectName
     */
    public function testSetObjectName(): void
    {
        $this->assertEquals(
            \get_class($this->object).'@test',
            $this->object->setObjectName(),
        );
    }
}
