<?php

declare(strict_types=1);

/**
 * This file is part of the EaseHtml package
 *
 * https://github.com/VitexSoftware/php-ease-html
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Ease\Html;

use Ease\Html\HeadTag;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:44.
 */
class HeadTagTest extends PairTagTest
{
    public string $rendered = '<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title></title></head>';
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new HeadTag();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \Ease\Html\HeadTag::setObjectName
     *
     * @todo   Implement testSetObjectName().
     */
    public function testSetObjectName(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Ease\Html\HeadTag::jsEnclosure
     *
     * @todo   Implement testJsEnclosure().
     */
    public function testJsEnclosure(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Ease\Html\HeadTag::finalize
     *
     * @todo   Implement testFinalize().
     */
    public function testFinalize(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Ease\Html\HeadTag::draw
     *
     * @param null|mixed $whatWant
     */
    public function testDraw($whatWant = null): void
    {
        \Ease\WebPage::singleton()->cascadeStyles = [];
        \Ease\Document::singleton()->javaScripts = [];
        parent::testDraw($whatWant);
    }

    /**
     * @covers \Ease\Html\HeadTag::drawIfNotDrawn
     *
     * @param mixed $canBeEmpty
     */
    public function testDrawIfNotDrawn($canBeEmpty = false): void
    {
        ob_start();
        $this->object->draw();
        $drawed = ob_get_contents();
        ob_end_clean();
        $this->assertNotEmpty($drawed);
    }
}
