<?php

declare (strict_types=1);

namespace Test\Ease\Html;

use Ease\Html\InputSearchTag;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:42.
 */
class InputSearchTagTest extends InputTagTest {

    /**
     * @var InputSearchTag
     */
    protected $object;
    public $rendered = '<input name="test" type="search" value="query" />';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new \Ease\Html\InputSearchTag('test', 'query');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * 
     * @covers Ease\Html\InputSearchTag::__construct
     */
    public function testConstructor() {
        $classname = get_class($this->object);

        // Get mock, without the constructor being called
        $mock = $this->getMockBuilder($classname)
                ->disableOriginalConstructor()
                ->getMockForAbstractClass();

        $mock->__construct('Tag', 'query', ['name' => 'Tag', 'id' => 'testing']);

        $this->assertEquals('<input name="Tag" id="testing" type="search" value="query" />',
                $mock->getRendered());
    }

    /**
     * 
     * @covers Ease\Html\InputSearchTag::draw
     */
    public function testDraw($whatWant = null) {
        parent::testDraw($this->rendered);
    }

}
