<?php

namespace Test\Ease\Html;

use Ease\Html\InputDateTimeTag;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-11-15 at 09:44:52.
 */
class InputDateTimeTagTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var InputDateTimeTag
     */
    protected $object;
    public $rendered = '<input name="when" type="date" value="DATE" />';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
     $this->rendered = strReplace('DATE', date('Y-m-d') , $this->rendered);
        $this->object = new InputDateTimeTag();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

}
