<?php

namespace Ease\Html;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-09-06 at 00:00:12.
 */
class InputDateTagTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var InputDateTag
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new InputDateTag;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }
}
