<?php

namespace Test\Ease\Html;

use Ease\Html\InputRadioTag;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:56.
 */
class InputRadioTagTest extends InputTagTest
{
    /**
     * @var InputRadioTag
     */
    protected $object;
    public $rendered = '<input name="choose" value="test" type="radio" />';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Ease\Html\InputRadioTag('choose', 'test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * 
     * @covers Ease\Html\InputRadioTag::__construct
     */
    public function testConstructor()
    {
        $classname = get_class($this->object);

        // Get mock, without the constructor being called
        $mock = $this->getMockBuilder($classname)
            ->disableOriginalConstructor()
            ->getMockForAbstractClass();

        $mock->__construct('Tag', 'test', ['name' => 'Tag', 'id' => 'testing']);

        $this->assertEquals('<input name="Tag" value="test" id="testing" type="radio" />',
            $mock->getRendered());
    }

    /**
     * @covers Ease\Html\InputRadioTag::setValue
     *
     * @todo   Implement testSetValue().
     */
    public function testSetValue()
    {
        $this->object->setValue('test');
        $this->assertEquals('<input name="choose" value="test" type="radio" checked />',
            $this->object->getRendered());
    }

    /**
     * 
     * @covers Ease\Html\InputRadioTag::draw
     */
    public function testDraw($whatWant = null)
    {
        parent::testDraw($this->rendered);
    }
}
