<?php

declare (strict_types=1);

namespace Test\Ease\Html;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:51.
 */
class InputHiddenTagTest extends InputTagTest {

    /**
     * @var InputHiddenTag
     */
    protected $object;
    public $rendered = '<input name="test" value="value" type="hidden" />';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new \Ease\Html\InputHiddenTag('test', 'value');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * 
     * @covers Ease\Html\InputHiddenTag::__construct
     */
    public function testConstructor() {
        $classname = get_class($this->object);

        // Get mock, without the constructor being called
        $mock = $this->getMockBuilder($classname)
                ->disableOriginalConstructor()
                ->getMockForAbstractClass();

        $mock->__construct('Tag', 'info@vitexsoftware.cz', ['name' => 'Tag', 'id' => 'testing']);

        $this->assertEquals('<input name="Tag" value="info@vitexsoftware.cz" id="testing" type="hidden" />',
                $mock->getRendered());
    }

}
