<?php
declare (strict_types=1);

namespace Test\Ease\Html;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:39.
 */
class InputFileTagTest extends InputTagTest
{
    /**
     * @var InputFileTag
     */
    protected $object;
    public $rendered = '<input name="test" type="file" />';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Ease\Html\InputFileTag('test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * 
     * @covers Ease\Html\InputFileTag::__construct
     */
    public function testConstructor()
    {
        $classname = get_class($this->object);

        // Get mock, without the constructor being called
        $mock = $this->getMockBuilder($classname)
            ->disableOriginalConstructor()
            ->getMockForAbstractClass();
        $mock->__construct('Test');

        $mock->__construct('Tag', 'file.txt', ['name' => 'Tag', 'id' => 'testing']);

        $this->assertEquals('<input name="Tag" type="file" value="file.txt" id="testing" />',
            $mock->getRendered());
    }
    
    
    /**
     * @covers Ease\Html\InputFileTag::draw
     */
    public function testDraw($whatWant = null)
    {
        parent::testDraw('
<input name="test" type="file" />');
    }

}
