<?php

namespace Test\Ease\Html;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:49.
 */
class SelectTagTest extends PairTagTest
{
    /**
     * @var SelectTag
     */
    protected $object;
    public $rendered = '<select name="test"><option value="a">A</option><option value="b">B</option></select>';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Ease\Html\SelectTag('test',
            ['a' => 'A', 'b' => 'B']);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers Ease\Html\Select::addItems
     */
    public function testAddItems()
    {
        $this->object->addItems(['a' => 'b', 'c' => 'd']);
    }

    /**
     * @covers Ease\Html\Select::addValue
     */
    public function testAddValue()
    {
        $this->object->addValue('test');
    }

    /**
     * @covers Ease\Html\Select::loadItems
     */
    public function testLoadItems()
    {
        $this->object->loadItems();
    }

    /**
     * @covers Ease\Html\Select::setValue
     */
    public function testSetValue()
    {
        $this->object->setValue('b');
        $this->assertEquals('<select name="test"><option value="a">A</option><option value="b" selected>B</option></select>',
            $this->object->getRendered());
    }

    /**
     * @covers Ease\Html\Select::finalize
     */
    public function testFinalize()
    {
        $this->object->finalize();
    }

    /**
     * @covers Ease\Html\Select::delItem
     */
    public function testDelItem()
    {
        $this->object->delItem();
    }

    /**
     * @covers Ease\Html\InputTag::getTagName
     */
    public function testGetTagName()
    {
        $this->assertEquals('test', $this->object->getTagName());
        $this->object->setName = true;
        $this->object->setTagName('Test');
        $this->assertEquals('Test', $this->object->getTagName());
    }
}
