docs/classes/*		usr/share/doc/php-vitexsoftware-ease-html/html/classes
docs/css/*		usr/share/doc/php-vitexsoftware-ease-html/html/css
docs/files/*		usr/share/doc/php-vitexsoftware-ease-html/html/files
docs/graphs/*		usr/share/doc/php-vitexsoftware-ease-html/html/graphs
docs/index.html		usr/share/doc/php-vitexsoftware-ease-html/html/
docs/indices/*		usr/share/doc/php-vitexsoftware-ease-html/html/indices
docs/js/*		usr/share/doc/php-vitexsoftware-ease-html/html/js
docs/namespaces/*		usr/share/doc/php-vitexsoftware-ease-html/html/namespaces
docs/packages/*		usr/share/doc/php-vitexsoftware-ease-html/html/packages
docs/reports/*		usr/share/doc/php-vitexsoftware-ease-html/html/reports

debian/php-vitexsoftware-ease-html-doc.conf	etc/apache2/conf-available/
README.md			usr/share/doc/php-vitexsoftware-ease-html

