<?php

namespace Test\Ease;

use Ease\Part;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-12-22 at 17:13:37.
 */
class PartTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Part
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Part();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers Ease\Part::setPartName
     * @todo   Implement testsetPartName().
     */
    public function testsetPartName() {
        $this->assertEquals('', $this->object->setPartName());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Ease\Part::onDocumentReady
     * @todo   Implement testonDocumentReady().
     */
    public function testonDocumentReady() {
        $this->assertEquals('', $this->object->onDocumentReady());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Ease\Part::finalize
     * @todo   Implement testfinalize().
     */
    public function testfinalize() {
        $this->assertEquals('', $this->object->finalize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Ease\Part::jQueryze
     * @todo   Implement testjQueryze().
     */
    public function testjQueryze() {
        $this->assertEquals('', $this->object->jQueryze());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Ease\Part::setPartProperties
     * @todo   Implement testsetPartProperties().
     */
    public function testsetPartProperties() {
        $this->assertEquals('', $this->object->setPartProperties());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Ease\Part::getPartPropertiesToString
     * @todo   Implement testgetPartPropertiesToString().
     */
    public function testgetPartPropertiesToString() {
        $this->assertEquals('', $this->object->getPartPropertiesToString());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Ease\Part::partPropertiesToString
     * @todo   Implement testpartPropertiesToString().
     */
    public function testpartPropertiesToString() {
        $this->assertEquals('', $this->object->partPropertiesToString());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
