<?php

namespace Test\Ease;

use Ease\Part;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-12-22 at 17:13:37.
 */
class PartTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Part
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Part();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers Ease\Part::setPartName
     */
    public function testsetPartName() {
        $testName = 'testDiv';
        $this->object->setPartName($testName);
        $this->assertEquals($testName, $this->object->partName);
    }

    /**
     * @covers Ease\Part::onDocumentReady
     */
    public function testonDocumentReady() {
        $this->assertEquals('', $this->object->onDocumentReady());
    }

    /**
     * @covers Ease\Part::finalize
     */
    public function testfinalize() {
        $this->assertEquals('', $this->object->finalize());
    }

    /**
     * @covers Ease\Part::jQueryze
     */
    public function testjQueryze() {
        $this->assertEquals('', $this->object->jQueryze());
    }

    /**
     * @covers Ease\Part::setPartProperties
     */
    public function testsetPartProperties() {
        $testProps = ['class' => 'myClass', 'id' => 'myId'];
        $this->object->setPartProperties($testProps);
        $this->assertEquals($testProps, $this->object->partProperties);
    }

    /**
     * @covers Ease\Part::getPartPropertiesToString
     */
    public function testgetPartPropertiesToString() {
        $this->assertEquals('', $this->object->getPartPropertiesToString());
    }

    /**
     * @covers Ease\Part::partPropertiesToString
     */
    public function testpartPropertiesToString() {
        $testProps = ['class' => 'myClass', 'id' => 'myId'];
        $result = \Ease\Part::partPropertiesToString($testProps);
        $this->assertIsString($result);
        $this->assertStringContainsString('myClass', $result);
        $this->assertStringContainsString('myId', $result);
    }
}
